In [2]:
import numpy as np

creating

In [3]:
x1 = np.array([1,2,3,4])
print(x1)
print(x1.shape)
print(x1.ndim)
print(type(x1))

[1 2 3 4]
(4,)
1
<class 'numpy.ndarray'>


In [4]:
x2 = np.array([
    [1,2,3],
    [4,5,6]
])
print(x2)
print(x2.shape)
print(x2.ndim)

[[1 2 3]
 [4 5 6]]
(2, 3)
2


In [5]:
a = np.arange(10, 51, .5)
print(a)

[10.  10.5 11.  11.5 12.  12.5 13.  13.5 14.  14.5 15.  15.5 16.  16.5
 17.  17.5 18.  18.5 19.  19.5 20.  20.5 21.  21.5 22.  22.5 23.  23.5
 24.  24.5 25.  25.5 26.  26.5 27.  27.5 28.  28.5 29.  29.5 30.  30.5
 31.  31.5 32.  32.5 33.  33.5 34.  34.5 35.  35.5 36.  36.5 37.  37.5
 38.  38.5 39.  39.5 40.  40.5 41.  41.5 42.  42.5 43.  43.5 44.  44.5
 45.  45.5 46.  46.5 47.  47.5 48.  48.5 49.  49.5 50.  50.5]


In [6]:
b = np.linspace(10,15, 25)
print(b)

[10.         10.20833333 10.41666667 10.625      10.83333333 11.04166667
 11.25       11.45833333 11.66666667 11.875      12.08333333 12.29166667
 12.5        12.70833333 12.91666667 13.125      13.33333333 13.54166667
 13.75       13.95833333 14.16666667 14.375      14.58333333 14.79166667
 15.        ]


In [7]:
c = np.random.randint(-10,10, (5,5))
print(c)

[[  2 -10  -3   1  -6]
 [  3  -8   2  -7   0]
 [ -2   2  -2  -7   2]
 [ -2   0   7  -5   3]
 [ -9  -6   0   8   6]]


In [ ]:
# creating array from a iterator 

list_b = 

In [9]:
a = np.array ([20,30,40,50])

b = np.arange(4)  

c = a-b
print(a) 
print(b) 
print(c) 

[20 30 40 50]
[0 1 2 3]
[20 29 38 47]


In [11]:
b**2 

10*np.sin(a)

e = a<35

print(b)
print(a)
print(e)

[0 1 2 3]
[20 30 40 50]
[ True  True False False]


In [15]:
A = np.array([[1,1], [0,1]])
B = np.array([[2,0],[3,4]])

prod1 = A * B

prod2 = A @ B

prod3 = A.dot(B)

print(prod1)
print(prod2)
print(prod3)


[[2 0]
 [0 4]]
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]


indexing & slicing 

In [16]:
def f(x,y):
    return 10*x+y

In [23]:
b = np.fromfunction(f,(5,4),dtype=int)
print(b)

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]


In [19]:
b[2,3]

23

Stacking Arrays

In [20]:
a = np.floor(10*np.random.random((2,2)))
b = np.floor(10*np.random.random((2,2)))

In [21]:
# stacking vertically 
np.vstack((a,b))

array([[0., 2.],
       [4., 9.],
       [3., 8.],
       [8., 5.]])

In [22]:
# horizontal stacking
np.hstack((a,b))

array([[0., 2., 3., 8.],
       [4., 9., 8., 5.]])

Splitting Arrays 

In [25]:
x = np.linspace(10,99,100).reshape(10,10).astype(int)
x 

array([[10, 10, 11, 12, 13, 14, 15, 16, 17, 18],
       [18, 19, 20, 21, 22, 23, 24, 25, 26, 27],
       [27, 28, 29, 30, 31, 32, 33, 34, 35, 36],
       [36, 37, 38, 39, 40, 41, 42, 43, 44, 45],
       [45, 46, 47, 48, 49, 50, 51, 52, 53, 54],
       [54, 55, 56, 57, 58, 59, 60, 61, 62, 63],
       [63, 64, 65, 66, 67, 68, 69, 70, 71, 72],
       [72, 73, 74, 75, 76, 77, 78, 79, 80, 81],
       [81, 82, 83, 84, 85, 86, 87, 88, 89, 90],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [27]:
print(x[:-3,-3:])

[[16 17 18]
 [25 26 27]
 [34 35 36]
 [43 44 45]
 [52 53 54]
 [61 62 63]
 [70 71 72]]


In [28]:
print(x[0,0]) # first element
print(x[-1,-1]) # last element
print(x[5,7]) # 5 row & 7 column index
# row 
print(x[0]) # first row
print(x[-1]) # last row 

10
99
61
[10 10 11 12 13 14 15 16 17 18]
[90 91 92 93 94 95 96 97 98 99]


In [29]:
print(x[:, 0]) # first column
print(x[:, -1]) # last column

[10 18 27 36 45 54 63 72 81 90]
[18 27 36 45 54 63 72 81 90 99]
